<div id="divResultado">	
	<table class="tabResultado">
		<tr>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			
		</tr>
		<tr>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			
		</tr>
		<tr>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			
		</tr>
		<tr>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			<th>Exemplo</th>
			
		</tr>
	</table>
</div>


